appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 5MwuihgorknXKTBuQrf3SYYSTls976PM3UiWbQzrHqGlOXP4WBrDxKbFFdieEUE3tUrvPDtV2oeb+Tcpbedt7HMWT/bEwDeV66WMXO0be+rJRyXbU60nqIGcJbSeZSzsV7yI0mEPrHx6qDLXBBCKQXH7UWYYZPtF+YAliQS88dmmrDFAgHeJVvzbrrcMj6GE4Ucme1xCIz4aR2KfnBGGyz5tL5tvLTu2jRoX1hwxXA+Ukt97PggAZxJMMXfUoT/BUSslb+Q2zz6py7HY7zp+at+mnAjJePUGsk/oojMlhWdagfvsRnOMvL6CmBqGXtiLdihkTaDxtw3xZkMBqtQ/vmeHuhgd3vUJN/ijeVIJ6lzBWgBgDHb8MHlEuoIeqPWsHWavy7aTeuwnxLTGkEHkz/qtglTCtSGSXRFhg6Z1FbroCPuiCAdgL10DbGMsAMHfTFimQz+slyV89mAuD2Lb0IMam573hso3BnOIIa5HOj5HvwC50M3QTIE5GC5mBItpZkSX/0hLDckVeiD/tdAQJ6HhrYx40tUjeCDdoZz+Uu7EP4bv9llJ5QnPfPtI/J9LmtLedUIuqIHKuCO1WAAoel6uWYaQ9Z2GOb/G+bP1RBBHdjTvA+hhhIWtWMx/4X4yag8DnnEwT5/VUzkvRc1s8E5iJ5rvyttNOkGCpCHXBhk=}
